name: data-card

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Use juejin-card
        uses: lxKylin/juejin-card@main
        # run: npm install && npm run start
        with:
          params: ${{ secrets.JUEJIN_PARAMS }}
